[tox]
; Minimum version of Tox
minversion = 1.8
envlist =
    ; https://docs.djangoproject.com/en/6.0/faq/install/#what-python-version-can-i-use-with-django
    py3{10,11,12,13,14}-dj52
    py3{12,13,14}-dj{60,main}

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[gh-actions:env]
DJANGO =
    5.2: dj52
    6.0: dj60
    main: djmain

[testenv]
commands =
    python3 tests/generate_mmdb.py
    coverage run {envbindir}/django-admin test -v 2 --pythonpath=./ --settings=tests.settings
    coverage report
    coverage xml
deps =
    coverage
    dj52: Django>=5.2,<6.0
    dj60: Django>=6.0,<6.1
    djmain: https://github.com/django/django/archive/main.tar.gz
    geoip2
    mmdb-writer
ignore_outcome =
    djmain: True
