# Generated by Django 1.11.29 on 2020-11-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0003_auto_20161205_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='namespace',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
