# Generated by Django 4.2.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0003_auto_20161205_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='expire_date',
            field=models.DateTimeField(db_index=True, verbose_name='expire date'),
        ),
    ]
